using Zenject;

namespace {PREFIX}.{NAME}.Installers
{
    public class {NAME}Installer: Installer<{NAME}Installer>
    {
        public override void InstallBindings()
        {
            // <RiskyGenerator.Resources> Autogenerated comment, do not remove

            // <RiskyGenerator.Services> Autogenerated comment, do not remove

            // <RiskyGenerator.Components> Autogenerated comment, do not remove
        }
    }
}