﻿using Zenject;
using {PREFIX}.{NAME}.Services;
using {PREFIX}.{NAME}.Interfaces;

namespace {PREFIX}.{NAME}.Installers
{
    public class {NAME}Installer: Installer<{NAME}Installer>
    {
        public override void InstallBindings()
        {
            // Autogenerated comment, do not remove
            // <RiskyGenerator.Resources>

            // Autogenerated comment, do not remove
            // <RiskyGenerator.Services>

            // Autogenerated comment, do not remove
            // <RiskyGenerator.Components>
        }
    }
}