using Zenject;
using {PREFIX}.{NAME}.Services;
using {PREFIX}.{NAME}.Interfaces;
// Autogenerated comment, do not remove
// <RiskyCLI.Usings>

namespace {PREFIX}.{NAME}.Installers
{
    public class {NAME}Installer: Installer<{NAME}Installer>
    {
        public override void InstallBindings()
        {
            // Autogenerated comment, do not remove
            // <RiskyCLI.Resources>

            // Autogenerated comment, do not remove
            // <RiskyCLI.Services>

            // Autogenerated comment, do not remove
            // <RiskyCLI.Components>
        }
    }
}